#!/usr/bin/env bash
set -euo pipefail

toks_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
cd "$toks_root"

toks_errors=0
toks_source_count=0
declare -A toks_legacy_lines=()
declare -A toks_legacy_internal_wildcards=()
declare -A toks_legacy_public_wildcards=()

while IFS=$'\t' read -r toks_path toks_lines toks_internal toks_public; do
    [[ -n "$toks_path" && "$toks_path" != \#* ]] || continue
    toks_legacy_lines["$toks_path"]=$toks_lines
    toks_legacy_internal_wildcards["$toks_path"]=$toks_internal
    toks_legacy_public_wildcards["$toks_path"]=$toks_public
done < scripts/quality/legacy-ingest-budget.tsv

toks_is_test_file() {
    case "$1" in
        */tests/* | */tests.rs | *_test.rs | *_tests.rs) return 0 ;;
        *) return 1 ;;
    esac
}

toks_is_generated_file() {
    case "$1" in
        */generated/* | *.generated.rs)
            head -n 5 "$1" | grep -Eq '(@generated|DO NOT EDIT|generated by)'
            ;;
        *) return 1 ;;
    esac
}

while IFS= read -r -d '' toks_file; do
    [[ -f "$toks_file" ]] || continue
    toks_source_count=$((toks_source_count + 1))
    if toks_is_generated_file "$toks_file"; then
        continue
    fi

    toks_lines=$(awk 'END { print NR }' "$toks_file")
    if toks_is_test_file "$toks_file"; then
        if ((toks_lines >= 500)); then
            echo "test file must stay below 500 lines: $toks_file ($toks_lines)" >&2
            toks_errors=$((toks_errors + 1))
        fi
        continue
    fi

    if ((toks_lines >= 200)); then
        toks_budget=${toks_legacy_lines["$toks_file"]:-0}
        if ((toks_budget == 0 || toks_lines > toks_budget)); then
            echo "production file must stay below 200 lines: $toks_file ($toks_lines)" >&2
            toks_errors=$((toks_errors + 1))
        fi
    fi

    toks_internal_count=$(grep -Ec '^[[:space:]]*(pub([[:space:]]*\([^)]*\))?[[:space:]]+)?use[[:space:]]+(crate|self|super)(::[[:alnum:]_]+)*::\*;' "$toks_file" || true)
    toks_internal_budget=${toks_legacy_internal_wildcards["$toks_file"]:-0}
    if ((toks_internal_count > toks_internal_budget)); then
        echo "internal wildcard import is not allowed: $toks_file" >&2
        toks_errors=$((toks_errors + 1))
    fi
    toks_public_count=$(grep -Ec '^[[:space:]]*pub([[:space:]]*\([^)]*\))?[[:space:]]+use[[:space:]].*::\*;' "$toks_file" || true)
    toks_public_budget=${toks_legacy_public_wildcards["$toks_file"]:-0}
    if ((toks_public_count > toks_public_budget)); then
        echo "wildcard re-export is not allowed: $toks_file" >&2
        toks_errors=$((toks_errors + 1))
    fi
done < <(git ls-files -co --exclude-standard -z -- '*.rs')

while IFS= read -r -d '' toks_file; do
    [[ -f "$toks_file" ]] || continue
    if grep -nE '/(home|Users)/[^/[:space:]]+/' "$toks_file" >/dev/null; then
        echo "developer-specific absolute path is not allowed: $toks_file" >&2
        toks_errors=$((toks_errors + 1))
    fi
done < <(git ls-files -co --exclude-standard -z -- \
    '.cargo/*.toml' 'assets/*.desktop' 'install.sh' 'README.md' 'AGENTS.md')

if ! grep -qx 'Exec=toks' assets/toks.desktop; then
    echo "desktop template must keep a portable Exec=toks entry" >&2
    toks_errors=$((toks_errors + 1))
fi
if ! grep -qx 'TryExec=toks' assets/toks.desktop; then
    echo "desktop template must keep a portable TryExec=toks entry" >&2
    toks_errors=$((toks_errors + 1))
fi

if ((toks_errors > 0)); then
    echo "repository quality check failed with $toks_errors issue(s)" >&2
    exit 1
fi

echo "repository quality check passed ($toks_source_count Rust files)"
