#!/usr/bin/env bash
set -euo pipefail

tokscope_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
cd "$tokscope_root"

tokscope_errors=0
tokscope_source_count=0
declare -A tokscope_legacy_lines=()
declare -A tokscope_legacy_internal_wildcards=()
declare -A tokscope_legacy_public_wildcards=()

while IFS=$'\t' read -r tokscope_path tokscope_lines tokscope_internal tokscope_public; do
    [[ -n "$tokscope_path" && "$tokscope_path" != \#* ]] || continue
    tokscope_legacy_lines["$tokscope_path"]=$tokscope_lines
    tokscope_legacy_internal_wildcards["$tokscope_path"]=$tokscope_internal
    tokscope_legacy_public_wildcards["$tokscope_path"]=$tokscope_public
done < scripts/quality/legacy-ingest-budget.tsv

tokscope_is_test_file() {
    case "$1" in
        */tests/* | */tests.rs | *_test.rs | *_tests.rs) return 0 ;;
        *) return 1 ;;
    esac
}

tokscope_is_generated_file() {
    case "$1" in
        */generated/* | *.generated.rs)
            head -n 5 "$1" | grep -Eq '(@generated|DO NOT EDIT|generated by)'
            ;;
        *) return 1 ;;
    esac
}

while IFS= read -r -d '' tokscope_file; do
    [[ -f "$tokscope_file" ]] || continue
    tokscope_source_count=$((tokscope_source_count + 1))
    if tokscope_is_generated_file "$tokscope_file"; then
        continue
    fi

    tokscope_lines=$(awk 'END { print NR }' "$tokscope_file")
    if tokscope_is_test_file "$tokscope_file"; then
        if ((tokscope_lines >= 500)); then
            echo "test file must stay below 500 lines: $tokscope_file ($tokscope_lines)" >&2
            tokscope_errors=$((tokscope_errors + 1))
        fi
        continue
    fi

    if ((tokscope_lines >= 200)); then
        tokscope_budget=${tokscope_legacy_lines["$tokscope_file"]:-0}
        if ((tokscope_budget == 0 || tokscope_lines > tokscope_budget)); then
            echo "production file must stay below 200 lines: $tokscope_file ($tokscope_lines)" >&2
            tokscope_errors=$((tokscope_errors + 1))
        fi
    fi

    tokscope_internal_count=$(grep -Ec '^[[:space:]]*(pub([[:space:]]*\([^)]*\))?[[:space:]]+)?use[[:space:]]+(crate|self|super)(::[[:alnum:]_]+)*::\*;' "$tokscope_file" || true)
    tokscope_internal_budget=${tokscope_legacy_internal_wildcards["$tokscope_file"]:-0}
    if ((tokscope_internal_count > tokscope_internal_budget)); then
        echo "internal wildcard import is not allowed: $tokscope_file" >&2
        tokscope_errors=$((tokscope_errors + 1))
    fi
    tokscope_public_count=$(grep -Ec '^[[:space:]]*pub([[:space:]]*\([^)]*\))?[[:space:]]+use[[:space:]].*::\*;' "$tokscope_file" || true)
    tokscope_public_budget=${tokscope_legacy_public_wildcards["$tokscope_file"]:-0}
    if ((tokscope_public_count > tokscope_public_budget)); then
        echo "wildcard re-export is not allowed: $tokscope_file" >&2
        tokscope_errors=$((tokscope_errors + 1))
    fi
done < <(git ls-files -co --exclude-standard -z -- '*.rs')

while IFS= read -r -d '' tokscope_file; do
    [[ -f "$tokscope_file" ]] || continue
    if grep -nE '/(home|Users)/[^/[:space:]]+/' "$tokscope_file" >/dev/null; then
        echo "developer-specific absolute path is not allowed: $tokscope_file" >&2
        tokscope_errors=$((tokscope_errors + 1))
    fi
done < <(git ls-files -co --exclude-standard -z -- \
    '.cargo/*.toml' 'assets/*.desktop' 'install.sh' 'README.md' 'AGENTS.md')

if ! grep -qx 'Exec=tokscope' assets/tokscope.desktop; then
    echo "desktop template must keep a portable Exec=tokscope entry" >&2
    tokscope_errors=$((tokscope_errors + 1))
fi
if ! grep -qx 'TryExec=tokscope' assets/tokscope.desktop; then
    echo "desktop template must keep a portable TryExec=tokscope entry" >&2
    tokscope_errors=$((tokscope_errors + 1))
fi

if ((tokscope_errors > 0)); then
    echo "repository quality check failed with $tokscope_errors issue(s)" >&2
    exit 1
fi

echo "repository quality check passed ($tokscope_source_count Rust files)"
